### ISSUE TITLE
Feature request: introducing a license to this project

### ISSUE THREAD

**Issue by almndbtr** [ourzora/zorb#17]
👋 Hello, @ourzora!

First things first: I'm a superfan of this project. Thank you for creating it! When I learned about it, I minted three in my excitement. 

- 🟣 [`#9144`](https://zorb.dev/nft/9144), [`#9160`](https://zorb.dev/nft/9160), [`#9206`](https://zorb.dev/nft/9206)

I'm wondering if you have any plans to [choose and implement a license](https://choosealicense.com/) for this project? As I understand it, there is currently [no license](https://choosealicense.com/no-permission/) and I think that means this work is under exclusive copyright by default. 💭

The reason I'm opening this is because I'm interested in contributing to the project! I learned a ton from [this Twitter thread with @iainnash](https://twitter.com/isiain/status/1477331850100101122?s=20) and I'd love to also write a contract walkthrough to help others (mainly me as someone new to the space 😆) how the on-chain SVG works.

Thanks for considering my request! 🙇

**Comment by almndbtr** [comment]
I noticed every package except for `zora-web-component` listed the MIT license in the `package.json` file, but I'm not confident that this "implicit" listing means that the entire project is licensed under MIT. 😅

* https://github.com/ourzora/zorb/blob/9ea4a500afd950a54c7411d72f81ec41cce642df/packages/zorb-contracts/package.json#L7
* https://github.com/ourzora/zorb/blob/9ea4a500afd950a54c7411d72f81ec41cce642df/packages/zorb-freezer-contracts/package.json#L7
* https://github.com/ourzora/zorb/blob/9ea4a500afd950a54c7411d72f81ec41cce642df/packages/zorb-web-site/package.json#L4

**Comment by iainnash** [comment]
Hey! The MIT license is wrong for the solidity.

We typically use MIT for public javascript code and GPLv3 for solidity.
Let me confirm with the team and add those licenses.

**Comment by almndbtr** [comment]
@iainnash - Sounds good to me. Thanks for considering my feedback! Happy to help wherever once you get the confirm. 🙇‍♂️

**Comment by iainnash** [comment]
The artwork license is TBD but solidity is gplv3 and js is MIT 👍

**Comment by almndbtr** [comment]
Gotcha. 👌 So, this is interesting! 😉

In my past experience, open source project license usually sit at [the root of the repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license). However, given that the Solidity code is in GPLv3 and the JS is in MIT, I'm unsure of what the best way to go about introducing these in a pull request, especially since this code belongs to @ourzora.

I'm wondering what you and the team think is the best way to proceed? That advice will help me form the PR. 👀

**Comment by almndbtr** [comment]
@iainnash - I gave it a shot in https://github.com/ourzora/zorb/pull/26. Happy to get feedback from the team and make any-and-all requested changes! :ear:
