### ISSUE TITLE
`onlyApproved` has a typo in its require messaging

### ISSUE THREAD

**Issue by almndbtr** [ourzora/zorb#18]
## Summary

🔬 I read through the `ZorbNFT.sol` contract and spotted this:

https://github.com/ourzora/zorb/blob/9ea4a500afd950a54c7411d72f81ec41cce642df/packages/zorb-contracts/contracts/ZorbNFT.sol#L99

I think `Ony` really be `Only` here? Cutting a PR now. ✌️

**Comment by iainnash** [comment]
Ahh good point! However, since this is deployed I think it may make sense to leave the repo as-is.

**Comment by almndbtr** [comment]
Gotcha, makes sense. I'll close this out! :v:
