### ISSUE TITLE
Enhancement: add an option to download the Zorb

### ISSUE THREAD

**Issue by almndbtr** [ourzora/zorb#20]
## Summary

Tons of folks are happy with these Zorbs! But, I noticed some didn't know how to have it as their profile photo. I think it would be wonderful to give them the option to download a Zorb from the viewer. 

If @ourzora team would be open to it, I can cut a PR for it once I'm done with my testing in https://github.com/almndbtr/zorb/pull/1. Here it is in action!

![zorb-download-spike](https://user-images.githubusercontent.com/78528185/147999727-eb17bff2-ff4f-44b3-a05f-038f1813c461.gif)

**Comment by almndbtr** [comment]
🏀 Shooting my shot in 2022: https://github.com/ourzora/zorb/pull/21

**Comment by iainnash** [comment]
Oh i like this!
