### ISSUE TITLE
Versioning: @zoralabs/zorb is 0.0.2 in NPM registry, but 0.0.1 in source

### ISSUE THREAD

**Issue by almndbtr** [ourzora/zorb#27]
🌓 Hiya @ourzora team!

`zora-web-component`'s `package.json` file's version is at 0.0.1:

https://github.com/ourzora/zorb/blob/a6563fe80917266befa4c4394b23e1996c0067e4/packages/zorb-web-component/package.json#L3

... but the published version in NPM is 0.0.2:

https://www.npmjs.com/package/@zoralabs/zorb

I'm wondering if/when the source will be updated to reflect this new version?

(I discovered this one while working on [a Zorb cookbook](https://github.com/almndbtr/zorb-cookbook) for fun/novel things folks can do with `@zoralabs/zorb`.)

**Comment by iainnash** [comment]
Fixed in #31
